spring:

  datasource:
    username: root
    password: 152704
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8


logging:
  level:
    root: info
  file:
    name: log/blog-pro.log


mybatis-plus:
  mapper-locations: classpath:com/atguigu/eduservice/mapper/xml/*.xml

server:
  port: 8081